services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DAPMyShelfBundle\Controller\:
        resource: "../../Controller"
        tags: ["controller.service_arguments"]
