version: "3.6"

services:
    web:
        container_name: folgerdap-client-web
        hostname: web
        build:
            context: .
            dockerfile: etc/docker/web/Dockerfile
        image: folgerdap/client/web
        ports:
            - "${APP_PORT:-8080}:80"
        working_dir: /app
        volumes:
            - ./etc/docker/web/default.conf:/etc/nginx/conf.d/default.conf:cached
        depends_on:
            - app
        restart: always
        networks:
            - public
            - app
    app:
        container_name: folgerdap-client-app
        hostname: app
        build:
            context: .
            dockerfile: etc/docker/app/Dockerfile
            target: ${TARGET_IMAGE:-dev}
        image: folgerdap/client/app
        expose:
            - 9000
        working_dir: /app
        volumes:
            - ./src:/app/src:cached
            - ./app:/app/app:cached
            - ./tests:/app/tests:cached
            - ./behat.yml:/app/behat.yml:cached
            - ./codeception.yml:/app/codeception.yml:cached
        environment:
            SYMFONY_DEBUG: ${SYMFONY_DEBUG:-1}
            SYMFONY_ENV: ${SYMFONY_ENV:-dev}
            GRAPHQL_API_ENDPOINT: ${GRAPHQL_API_ENDPOINT:-https://server.staging.collections.folger.edu}
            MANIFEST_ENDPOINT: ${MANIFEST_ENDPOINT:-https://server.staging.collections.folger.edu}
            APISESSION_ENDPOINT: ${APISESSION_ENDPOINT:-https://server.staging.collections.folger.edu}
            FRONTEND_URL: ${FRONTEND_URL:-https://static.collections.folger.edu/dap-client-frontend}
            FRONTEND_VERSION: ${FRONTEND_VERSION-1.12.9}
        restart: always
        networks:
            - app
            - server

networks:
    public:
        name: folgerdap-client-public
    app:
        name: folgerdap-client-app
    server:
        name: folgerdap-server-public
